### ISSUE TITLE
הוספת לוגים

### ISSUE THREAD

**Issue by mekavehamichlolay** [mekavehamichlolay/AspaklaryaLockdown#3]
יש צורך להוסיף לוג לכל הוספה, הסרה או שינוי מרשימת החסומים.
צריך להחליט אם להוסיף ליומן הראשי או לעשות יומן עצמאי (כמו מסנן ההשחתות).
צריך להחליט אם לעשות שהפעולות יוצגו רק לבעלי הרשאה מתאימה (כמו יומן בדיקת ip) או לכולם.

**Comment by mici-ym** [comment]
למה לא להציג לכולם?

**Comment by mekavehamichlolay** [comment]
> למה לא להציג לכולם?

יש שיקולים לכאן ולכאן. הדיון על כך מתנהל בפורום אחר 😉

**Comment by mekavehamichlolay** [comment]
הוספתי לתוך מיוחד יומנים הרגיל
